routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    
    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);
    Route::resource('rooms', 'Admin\RoomsController');
    Route::post('rooms_mass_destroy', ['uses' => 'Admin\RoomsController@massDestroy', 'as' => 'rooms.mass_destroy']);
    Route::resource('comments', 'Admin\CommentsController');
    Route::post('comments_mass_destroy', ['uses' => 'Admin\CommentsController@massDestroy', 'as' => 'comments.mass_destroy']);
    Route::post('comments_restore/{id}', ['uses' => 'Admin\CommentsController@restore', 'as' => 'comments.restore']);
    Route::delete('comments_perma_del/{id}', ['uses' => 'Admin\CommentsController@perma_del', 'as' => 'comments.perma_del']);
    Route::resource('likes', 'Admin\LikesController');
    Route::post('likes_mass_destroy', ['uses' => 'Admin\LikesController@massDestroy', 'as' => 'likes.mass_destroy']);
    Route::resource('bookings', 'Admin\BookingsController');
    Route::post('bookings_mass_destroy', ['uses' => 'Admin\BookingsController@massDestroy', 'as' => 'bookings.mass_destroy']);
    Route::post('/spatie/media/upload', 'Admin\SpatieMediaController@create')->name('media.upload');
    Route::post('/spatie/media/remove', 'Admin\SpatieMediaController@destroy')->name('media.remove');



 
});

app/Room.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMedia;

/**
 * Class Room
 *
 * @package App
 * @property string $title
 * @property string $info
 * @property string $location
 * @property decimal $price
 * @property integer $max_tenants
 * @property integer $view_count
 * @property string $is_available
*/
class Room extends Model implements HasMedia
{
    use HasMediaTrait;

    protected $fillable = ['title','owner', 'info', 'price', 'max_tenants', 'view_count', 'is_available', 'location_address', 'location_latitude', 'location_longitude'];
    protected $hidden = [];
    
    

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setPriceAttribute($input)
    {
        $this->attributes['price'] = $input ? $input : null;
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setMaxTenantsAttribute($input)
    {
        $this->attributes['max_tenants'] = $input ? $input : null;
    }

    /**
     * Set attribute to money format
     * @param $input
     */
    public function setViewCountAttribute($input)
    {
        $this->attributes['view_count'] = $input ? $input : null;
    }
    
    public function tenants()
    {
        return $this->belongsToMany(User::class, 'room_user');
    }
    
}

app/Http/Controllers/Admin/RoomsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Room;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreRoomsRequest;
use App\Http\Requests\Admin\UpdateRoomsRequest;
use App\Http\Controllers\Traits\FileUploadTrait;

class RoomsController extends Controller
{
    use FileUploadTrait;

    /**
     * Display a listing of Room.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (! Gate::allows('room_access')) {
            return abort(401);
        }


                $rooms = Room::all();

        return view('admin.rooms.index', compact('rooms'));
    }

    /**
     * Show the form for creating new Room.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if (! Gate::allows('room_create')) {
            return abort(401);
        }
        
        $tenants = \App\User::get()->pluck('name', 'id');


        return view('admin.rooms.create', compact('tenants'));
    }

    /**
     * Store a newly created Room in storage.
     *
     * @param  \App\Http\Requests\StoreRoomsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRoomsRequest $request)
    {
        if (! Gate::allows('room_create')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $room = Room::create($request->all());
        $room->tenants()->sync(array_filter((array)$request->input('tenants')));


        foreach ($request->input('photos_id', []) as $index => $id) {
            $model          = config('laravel-medialibrary.media_model');
            $file           = $model::find($id);
            $file->model_id = $room->id;
            $file->save();
        }

        return redirect()->route('admin.rooms.index');
    }


    /**
     * Show the form for editing Room.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (! Gate::allows('room_edit')) {
            return abort(401);
        }
        
        $tenants = \App\User::get()->pluck('name', 'id');


        $room = Room::findOrFail($id);

        return view('admin.rooms.edit', compact('room', 'tenants'));
    }

    /**
     * Update Room in storage.
     *
     * @param  \App\Http\Requests\UpdateRoomsRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateRoomsRequest $request, $id)
    {
        if (! Gate::allows('room_edit')) {
            return abort(401);
        }
        $request = $this->saveFiles($request);
        $room = Room::findOrFail($id);
        $room->update($request->all());
        $room->tenants()->sync(array_filter((array)$request->input('tenants')));


        $media = [];
        foreach ($request->input('photos_id', []) as $index => $id) {
            $model          = config('laravel-medialibrary.media_model');
            $file           = $model::find($id);
            $file->model_id = $room->id;
            $file->save();
            $media[] = $file->toArray();
        }
        $room->updateMedia($media, 'photos');

        return redirect()->route('admin.rooms.index');
    }


    /**
     * Display Room.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (! Gate::allows('room_view')) {
            return abort(401);
        }
        
        $tenants = \App\User::get()->pluck('name', 'id');
$bookings = \App\Booking::where('room_id', $id)->get();$likes = \App\Like::where('room_id', $id)->get();$comments = \App\Comment::where('room_id', $id)->get();

        $room = Room::findOrFail($id);

        return view('admin.rooms.show', compact('room', 'bookings', 'likes', 'comments'));
    }


    /**
     * Remove Room from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (! Gate::allows('room_delete')) {
            return abort(401);
        }
        $room = Room::findOrFail($id);
        $room->deletePreservingMedia();

        return redirect()->route('admin.rooms.index');
    }

    /**
     * Delete all selected Room at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        if (! Gate::allows('room_delete')) {
            return abort(401);
        }
        if ($request->input('ids')) {
            $entries = Room::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->deletePreservingMedia();
            }
        }
    }

}

app/Http/Controllers/Api/V1/RoomsController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Room;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreRoomsRequest;
use App\Http\Requests\Admin\UpdateRoomsRequest;
use App\Http\Controllers\Traits\FileUploadTrait;

class RoomsController extends Controller
{
    use FileUploadTrait;

    public function index(Request $request)
    {
        $page = (isset($request->page) ? $request->page : 1) ;
        $page = (($page <= 0) ? 1 : $page ) ;
        $limit = (isset($request->page_count) ? $request->page_count : 20 ) ;
        $skip =  ($page-1) * $limit ;
        $skip = abs( $skip);

        $items = Room::with('tenants');

        $pages_count = ceil(count($items->get()) / $limit);
        $items = $items->skip($skip)->take($limit)->get();
        foreach ($items as $item){
            foreach ($item->getMedia('photos') as $media) {
                $media['url']= asset('public'.$media->getUrl());
            }
        }

        $message ='Successful';
        $status  = true;
        $response = ['status' => $status ,'message' =>$message ,'items' =>$items,'page'=>$page , 'pages_count'=>$pages_count ];
        return response()->json($response);
    }

    public function show($id)
    {
        return Room::findOrFail($id);
        $item =Room::where('id',$item->id)->with('media')->first();
        if ($item){
            $status   = true;
            $message  = "Succefull";

        }else{
            $status  =false;
            $message ="Erorr No Rooms  inserted yet";
        }
        $response = ['status' => $status ,'message' =>$message ,'items' =>$item ];
        return response()->json($response);
    }

    public function update(UpdateRoomsRequest $request, $id)
    {
        $request = $this->saveFiles($request);
        $room = Room::findOrFail($id);
        $room->update($request->all());
        

        return $room;
    }


    public function store(StoreRoomsRequest $request)
    {
        $request = $this->saveFiles($request);
        $item = Room::create($request->all());
        if($item){
            //  dd($item->id);
            foreach ($request->input('photos_id', []) as $index => $id) {
                $model          = config('laravel-medialibrary.media_model');
                $file           = $model::find($id);
                $file->model_id = $item->id;
                $file->save();

            }
            $item_a =Room::where('id',$item->id)->with('media')->first();
            $status   = true;
            $message  = "Succefull";

        }else{
            $status  =false;
            $message ="Erorr No Items  inserted yet";
        }
        $response = ['status' => $status ,'message' =>$message ,'items' =>$item_a ];
        return response()->json($response);
    }

    public function destroy($id)
    {
        $room = Room::findOrFail($id);
        $room->delete();
        return '';
    }
}

resources/views/admin/rooms/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.rooms.title')</h3>
    @can('room_create')
    <p>
        <a href="{{ route('admin.rooms.create') }}" class="btn btn-success">@lang('global.app_add_new')</a>
        
    </p>
    @endcan

    

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($rooms) > 0 ? 'datatable' : '' }} @can('room_delete') dt-select @endcan">
                <thead>
                    <tr>
                        @can('room_delete')
                            <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>
                        @endcan

                        <th>@lang('global.rooms.fields.title')</th>
                        <th>@lang('global.rooms.fields.info')</th>
                        <th>@lang('global.rooms.fields.location')</th>
                        <th>@lang('global.rooms.fields.price')</th>
                        <th>@lang('global.rooms.fields.max-tenants')</th>
                        <th>@lang('global.rooms.fields.photos')</th>
                        <th>@lang('global.rooms.fields.tenants')</th>
                        <th>@lang('global.rooms.fields.view-count')</th>
                        <th>@lang('global.rooms.fields.is-available')</th>
                                                <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($rooms) > 0)
                        @foreach ($rooms as $room)
                            <tr data-entry-id="{{ $room->id }}">
                                @can('room_delete')
                                    <td></td>
                                @endcan

                                <td field-key='title'>{{ $room->title }}</td>
                                <td field-key='info'>{{ $room->info }}</td>
                                <td field-key='location'>{{ $room->location_address }}</td>
                                <td field-key='price'>{{ $room->price }}</td>
                                <td field-key='max_tenants'>{{ $room->max_tenants }}</td>
                                <td field-key='photos'> @foreach($room->getMedia('photos') as $media)
                                <p class="form-group">
                                    <a href="{{ $media->getUrl() }}" target="_blank">{{ $media->name }} ({{ $media->size }} KB)</a>
                                </p>
                            @endforeach</td>
                                <td field-key='tenants'>
                                    @foreach ($room->tenants as $singleTenants)
                                        <span class="label label-info label-many">{{ $singleTenants->name }}</span>
                                    @endforeach
                                </td>
                                <td field-key='view_count'>{{ $room->view_count }}</td>
                                <td field-key='is_available'>{{ $room->is_available }}</td>
                                                                <td>
                                    @can('room_view')
                                    <a href="{{ route('admin.rooms.show',[$room->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('room_edit')
                                    <a href="{{ route('admin.rooms.edit',[$room->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('room_delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.rooms.destroy', $room->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="14">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        @can('room_delete')
            window.route_mass_crud_entries_destroy = '{{ route('admin.rooms.mass_destroy') }}';
        @endcan

    </script>
@endsection

resources/views/admin/rooms/show.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.rooms.title')</h3>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_view')
        </div>

        <div class="panel-body table-responsive">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-bordered table-striped">
                        <tr>
                            <th>@lang('global.rooms.fields.title')</th>
                            <td field-key='title'>{{ $room->title }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.rooms.fields.info')</th>
                            <td field-key='info'>{{ $room->info }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.rooms.fields.location')</th>
                            <td field-key='location'>{{ $room->location_address }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.rooms.fields.price')</th>
                            <td field-key='price'>{{ $room->price }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.rooms.fields.max-tenants')</th>
                            <td field-key='max_tenants'>{{ $room->max_tenants }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.rooms.fields.photos')</th>
                            <td field-key='photos'> @foreach($room->getMedia('photos') as $media)
                                <p class="form-group">
                                    <a href="{{ $media->getUrl() }}" target="_blank">{{ $media->name }} ({{ $media->size }} KB)</a>
                                </p>
                            @endforeach</td>
                        </tr>
                        <tr>
                            <th>@lang('global.rooms.fields.tenants')</th>
                            <td field-key='tenants'>
                                @foreach ($room->tenants as $singleTenants)
                                    <span class="label label-info label-many">{{ $singleTenants->name }}</span>
                                @endforeach
                            </td>
                        </tr>
                        <tr>
                            <th>@lang('global.rooms.fields.view-count')</th>
                            <td field-key='view_count'>{{ $room->view_count }}</td>
                        </tr>
                        <tr>
                            <th>@lang('global.rooms.fields.is-available')</th>
                            <td field-key='is_available'>{{ $room->is_available }}</td>
                        </tr>
                    </table>
                </div>
            </div><!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
    
<li role="presentation" class="active"><a href="#booking" aria-controls="booking" role="tab" data-toggle="tab">Booking</a></li>
<li role="presentation" class=""><a href="#likes" aria-controls="likes" role="tab" data-toggle="tab">Likes</a></li>
<li role="presentation" class=""><a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
    
<div role="tabpanel" class="tab-pane active" id="booking">
<table class="table table-bordered table-striped {{ count($bookings) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('global.booking.fields.room')</th>
                        <th>@lang('global.booking.fields.user')</th>
                        <th>@lang('global.booking.fields.date')</th>
                        <th>@lang('global.booking.fields.status')</th>
                                                <th>&nbsp;</th>

        </tr>
    </thead>

    <tbody>
        @if (count($bookings) > 0)
            @foreach ($bookings as $booking)
                <tr data-entry-id="{{ $booking->id }}">
                    <td field-key='room'>{{ $booking->room->title or '' }}</td>
                                <td field-key='user'>{{ $booking->user->name or '' }}</td>
                                <td field-key='date'>{{ $booking->date }}</td>
                                <td field-key='status'>{{ $booking->status }}</td>
                                                                <td>
                                    @can('view')
                                    <a href="{{ route('bookings.show',[$booking->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('edit')
                                    <a href="{{ route('bookings.edit',[$booking->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['bookings.destroy', $booking->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="9">@lang('global.app_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
<div role="tabpanel" class="tab-pane " id="likes">
<table class="table table-bordered table-striped {{ count($likes) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('global.likes.fields.user')</th>
                        <th>@lang('global.likes.fields.room')</th>
                                                <th>&nbsp;</th>

        </tr>
    </thead>

    <tbody>
        @if (count($likes) > 0)
            @foreach ($likes as $like)
                <tr data-entry-id="{{ $like->id }}">
                    <td field-key='user'>{{ $like->user->name or '' }}</td>
                                <td field-key='room'>{{ $like->room->title or '' }}</td>
                                                                <td>
                                    @can('view')
                                    <a href="{{ route('likes.show',[$like->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('edit')
                                    <a href="{{ route('likes.edit',[$like->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['likes.destroy', $like->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>

                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="7">@lang('global.app_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
<div role="tabpanel" class="tab-pane " id="comments">
<table class="table table-bordered table-striped {{ count($comments) > 0 ? 'datatable' : '' }}">
    <thead>
        <tr>
            <th>@lang('global.comments.fields.comment')</th>
                        <th>@lang('global.comments.fields.user')</th>
                        <th>@lang('global.comments.fields.room')</th>
                        <th>@lang('global.comments.fields.rate')</th>
                        @if( request('show_deleted') == 1 )
                        <th>&nbsp;</th>
                        @else
                        <th>&nbsp;</th>
                        @endif
        </tr>
    </thead>

    <tbody>
        @if (count($comments) > 0)
            @foreach ($comments as $comment)
                <tr data-entry-id="{{ $comment->id }}">
                    <td field-key='comment'>{!! $comment->comment !!}</td>
                                <td field-key='user'>{{ $comment->user->name or '' }}</td>
                                <td field-key='room'>{{ $comment->room->title or '' }}</td>
                                <td field-key='rate'>{{ $comment->rate }}</td>
                                @if( request('show_deleted') == 1 )
                                <td>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'POST',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['comments.restore', $comment->id])) !!}
                                    {!! Form::submit(trans('global.app_restore'), array('class' => 'btn btn-xs btn-success')) !!}
                                    {!! Form::close() !!}
                                                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['comments.perma_del', $comment->id])) !!}
                                    {!! Form::submit(trans('global.app_permadel'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                                                </td>
                                @else
                                <td>
                                    @can('view')
                                    <a href="{{ route('comments.show',[$comment->id]) }}" class="btn btn-xs btn-primary">@lang('global.app_view')</a>
                                    @endcan
                                    @can('edit')
                                    <a href="{{ route('comments.edit',[$comment->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    @endcan
                                    @can('delete')
{!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['comments.destroy', $comment->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                                @endif
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="9">@lang('global.app_no_entries_in_table')</td>
            </tr>
        @endif
    </tbody>
</table>
</div>
</div>

            <p>&nbsp;</p>

            <a href="{{ route('admin.rooms.index') }}" class="btn btn-default">@lang('global.app_back_to_list')</a>
        </div>
    </div>
@stop